(function () {
  const NS = window.DemoFreeAudit = window.DemoFreeAudit || {};

  const Modal = antd.Modal;
  const message = antd.message;
  const freeauditUtils = window.__DEMO_FREEAUDIT_UTILS || {};
  const getFreeAuditQuery = freeauditUtils.getFreeAuditQuery || function () { return {}; };
  const presetSuggestions = freeauditUtils.presetSuggestions || [];
  const CHAT_DEMO_SCENARIOS = freeauditUtils.CHAT_DEMO_SCENARIOS || [];
  const WORKBENCH_PROJECT_NAME_BY_ID = freeauditUtils.WORKBENCH_PROJECT_NAME_BY_ID || {};
  const SUMMARY_RESPONSE_DEMO = freeauditUtils.SUMMARY_RESPONSE_DEMO || '';
  const DEMO_RUN_SUMMARY_TEXT = freeauditUtils.DEMO_RUN_SUMMARY_TEXT || '';
  const demoToolDiffLineClass = freeauditUtils.demoToolDiffLineClass || function () { return 'nlm-tool-diff-line--ctx'; };
  const demoLinesUnifiedDiff = freeauditUtils.demoLinesUnifiedDiff || function () { return { lines: [], truncated: false }; };
  const toAnalysisTemplateShared = freeauditUtils.toAnalysisTemplateShared || function (seed) { return seed; };
  const buildWorkbenchMaterialAntTreeData = freeauditUtils.buildWorkbenchMaterialAntTreeData || function () { return { treeData: [], autoExpandKeys: [] }; };
  const buildWorkbenchAnalysisResultAntTreeData = freeauditUtils.buildWorkbenchAnalysisResultAntTreeData || function () { return { treeData: [], autoExpandKeys: [], initialExpandKeys: [] }; };
  const buildWorkbenchAnalysisResultFolderPickerTree = freeauditUtils.buildWorkbenchAnalysisResultFolderPickerTree || function () { return []; };
  const WB_TASK_CREATE_RESULT_OUTPUT_ROOT = freeauditUtils.WB_TASK_CREATE_RESULT_OUTPUT_ROOT || '__root__';
  const resolveWbTaskCreateResultOutputFolder = freeauditUtils.resolveWbTaskCreateResultOutputFolder || function () { return { folderId: null, folderLabel: '根目录' }; };
  const applyWorkbenchMaterialTreeDrop = freeauditUtils.applyWorkbenchMaterialTreeDrop || function () { return { ok: false, message: '未实现' }; };
  const applyWorkbenchAnalysisResultTreeDrop = freeauditUtils.applyWorkbenchAnalysisResultTreeDrop || function () { return { ok: false, message: '未实现' }; };
  const wbMatMaterialPathPrefixForRow = freeauditUtils.wbMatMaterialPathPrefixForRow || function () { return ''; };
  const wbMatAntTreeKey = freeauditUtils.wbMatAntTreeKey || function (k, id) { return `${k}:${id}`; };
  const DEMO_WORKBENCH_DB_CATALOGS = Object.freeze([
    {
      id: 'db-1',
      nameEn: 'fiscal_payment',
      name: '财政支付库',
      source: '核心业务库',
      owner: '数据中心',
      updatedAt: '2026-05-06 09:30:00',
      tables: Object.freeze([
        { name: 'payment_order', comment: '财政集中支付主单', rowCount: 124600, ddl: 'CREATE TABLE payment_order (id bigint, amount decimal(16,2), dept_name varchar(128));' },
        { name: 'payment_detail', comment: '支付明细与科目拆分', rowCount: 982000, ddl: 'CREATE TABLE payment_detail (order_id bigint, item_name varchar(128), amount decimal(16,2));' },
      ]),
    },
    {
      id: 'db-2',
      nameEn: 'contract_execution',
      name: '合同执行库',
      source: '合同管理系统',
      owner: '审计组A',
      updatedAt: '2026-05-05 15:20:00',
      tables: Object.freeze([
        { name: 'contract_main', comment: '合同主数据与履约状态', rowCount: 18630, ddl: 'CREATE TABLE contract_main (contract_no varchar(64), vendor_name varchar(128), signed_at datetime);' },
      ]),
    },
  ]);
  const DEMO_WORKBENCH_DB_RESOURCE_LIST = Object.freeze([
    {
      id: 'db-1::payment_order',
      databaseId: 'db-1',
      databaseName: '财政支付库',
      tableName: 'payment_order',
      name: 'payment_order',
      ddl: 'CREATE TABLE payment_order (id bigint, amount decimal(16,2), dept_name varchar(128));',
      comment: '财政集中支付主单',
      rowCount: 124600,
      source: '核心业务库',
      owner: '数据中心',
      updatedAt: '2026-05-08 05:42:35',
    },
    {
      id: 'db-1::payment_detail',
      databaseId: 'db-1',
      databaseName: '财政支付库',
      tableName: 'payment_detail',
      name: 'payment_detail',
      ddl: 'CREATE TABLE payment_detail (order_id bigint, item_name varchar(128), amount decimal(16,2));',
      comment: '支付明细与科目拆分',
      rowCount: 982000,
      source: '核心业务库',
      owner: '数据中心',
      updatedAt: '2026-05-08 05:42:35',
    },
    {
      id: 'db-2::contract_main',
      databaseId: 'db-2',
      databaseName: '合同执行库',
      tableName: 'contract_main',
      name: 'contract_main',
      ddl: 'CREATE TABLE contract_main (contract_no varchar(64), vendor_name varchar(128), signed_at datetime);',
      comment: '合同主数据与履约状态',
      rowCount: 18630,
      source: '合同管理系统',
      owner: '审计组A',
      updatedAt: '2026-05-08 05:42:35',
    },
  ]);
  const DEMO_WORKBENCH_GRAPH_RESOURCE_LIST = Object.freeze([
    { id: 'graph-1', name: '采购业务关系图谱', source: '内置图谱中心', entityCount: 1280, edgeCount: 4670, updatedAt: '2026-05-06 11:20:00' },
    { id: 'graph-2', name: '资金流向图谱', source: '内置图谱中心', entityCount: 960, edgeCount: 3320, updatedAt: '2026-05-04 16:45:00' },
  ]);
  const DEMO_WORKBENCH_GRAPH_CATALOGS = Object.freeze([
    { id: 'graph-1', name: '采购业务关系图谱', description: '覆盖采购申请、审批、合同与支付流转关系。', source: '内置图谱中心', entityCount: 1280, edgeCount: 4670, updatedAt: '2026-05-06 11:20:00' },
    { id: 'graph-2', name: '资金流向图谱', description: '展示预算科目、拨付批次与账户收支链路。', source: '内置图谱中心', entityCount: 960, edgeCount: 3320, updatedAt: '2026-05-04 16:45:00' },
    { id: 'graph-3', name: '合同履约风险图谱', description: '聚焦合同条款、里程碑节点与履约偏差风险。', source: '内置图谱中心', entityCount: 735, edgeCount: 2148, updatedAt: '2026-05-02 14:12:00' },
    { id: 'graph-4', name: '发票-付款关联图谱', description: '关联发票、付款单、供应商与银行流水核对。', source: '内置图谱中心', entityCount: 842, edgeCount: 2816, updatedAt: '2026-05-01 09:33:00' },
  ]);
  const DEMO_WORKBENCH_KNOWLEDGE_RESOURCE_LIST = Object.freeze([
    { id: 'kb-1', name: '审计制度知识库', scope: '组织级', status: 'coming_soon' },
  ]);

  NS.workbenchResourceSeeds = Object.freeze({
    dbResourceList: DEMO_WORKBENCH_DB_RESOURCE_LIST,
    graphResourceList: DEMO_WORKBENCH_GRAPH_RESOURCE_LIST,
    knowledgeResourceList: DEMO_WORKBENCH_KNOWLEDGE_RESOURCE_LIST,
  });

  NS.state = {
    createState() {
      return {
          freeAuditAiPolishKey: '',
          freeAuditPolishUndo: {},
          materials: [],
          materialSearchQuery: '',
          workbenchAnalysisSearchQuery: '',
          workbenchAnalysisSearchOpen: false,
          workbenchAnalysisResultSortMode: 'name',
          workbenchMaterialFilterPopoverOpen: false,
          workbenchMaterialSearchOpen: false,
          workbenchMaterialStatusView: 'all',
          workbenchBulkSelection: { area: null, scope: null, keys: [] },
          workbenchFileTreeExpandedKeys: [],
          workbenchAnalysisResultTreeExpandedKeys: [],
          wbUploadMaterialVisible: false,
          wbUploadMaterialSessionByProjectId: {},
          wbUploadMaterialSelectionByProjectId: {},
          wbUploadMaterialParentFolderByProjectId: {},
          wbCreateFolderModalOpen: false,
          wbCreateFolderForm: { name: '', parentFolderId: '' },
          wbCrossWorkbenchImportOpen: false,
          wbCrossWorkbenchImportSourceProjectId: '',
          wbCrossWorkbenchImportTab: 'file',
          wbCrossWorkbenchImportQuery: '',
          wbCrossWorkbenchImportSelectedKeys: [],
          wbCrossWorkbenchImportExpandedKeys: [],
          wbCrossWorkbenchImportTargetFolderId: '',
          wbCrossWorkbenchImportTargetOriginFolderId: '',
          wbDeleteFolderModalOpen: false,
          wbDeleteFolderTarget: null,
          wbArResultCreateFolderModalOpen: false,
          wbArResultCreateFolderName: '',
          /** @type {null | { type: 'root'|'underFolder', folderId?: string }} */
          wbArResultCreateFolderSpec: null,
          wbTaskResourcePreviewOpen: false,
          wbTaskResourcePreviewItem: null,
          wbTaskResourcePreviewResolvedMaterial: null,
          wbTaskResourcePreviewActiveTab: 'fields',
          wbTaskResourcePreviewOcrLines: false,
          workbenchDbSearchOpen: false,
          workbenchGraphSearchOpen: false,
          workbenchMaterialStatusPopoverOpenQueued: false,
          workbenchMaterialStatusPopoverOpenParsing: false,
          workbenchMaterialStatusPopoverOpenFailed: false,
          workbenchAnalysisStatusPopoverOpenQueued: false,
          workbenchAnalysisStatusPopoverOpenParsing: false,
          workbenchAnalysisStatusPopoverOpenFailed: false,
          workbenchProjectId: null,
          /** 点击「刷新」时递增，驱动技能等从 mock 的只读计算重新求值 */
          workbenchDemoRefreshTick: 0,
          _workbenchUploadTimers: {},
          _workbenchParseTimers: {},
          workbenchMaterialId: null,
          workbenchAnalysisResultId: null,
          workbenchReportId: null,
          workbenchAnalysisCitationPopover: { show: false, title: '', excerpt: '', x: 0, y: 0 },
          workbenchAnalysisCitationPopoverTimer: null,
          workbenchAnalysisEmbedDraft: '',
          _workbenchAnalysisEmbedSnap: '',
          /** 审计助手侧栏结果正文：按结果 id 存 Markdown 历史快照（演示），用于历史版本回退 */
          workbenchAnalysisVersionHistoryById: {},
          wbAnalysisResultMetaEditVisible: false,
          wbAnalysisResultMetaEditTargetId: '',
          wbAnalysisResultMetaEditForm: { name: '' },
          wbAnalysisModalEmbedDraft: '',
          _wbAnalysisModalEmbedSnap: '',
          wbMaterialMetaEditVisible: false,
          wbMaterialMetaEditTargetId: '',
          wbMaterialMetaEditForm: { name: '' },
          _wbMaterialMetaSnap: null,
          wbAnalysisModalOpen: false,
          wbAnalysisModalRecord: null,
          wbAnalysisModalActiveTab: 'basic',
          wbMaterialPreviewActiveTab: 'preview',
          /** 资料预览 · OCR 页：是否在正文左侧展示行号 */
          materialPreviewOcrShowLineNumbers: false,
          wbAnalysisResultPreviewActiveTab: 'body',
          wbAnalysisModalCitationPopover: { show: false, title: '', excerpt: '', x: 0, y: 0 },
          wbAnalysisModalCitationPopoverTimer: null,
          wbAnalysisHistoryDiffOpen: false,
          wbAnalysisHistoryDiffLines: [],
          wbAnalysisHistoryDiffTruncated: false,
          wbAnalysisVersionDetailVisible: false,
          wbAnalysisVersionDetailMarkdown: '',
          saveResultModalVisible: false,
          saveResultModalSourceType: 'message',
          saveResultModalSourceMsgId: null,
          saveResultModalSourcePayload: null,
          saveResultForm: { name: '' },
          chatMessages: [],
          chatInput: '',
          chatInputRefItems: [],
          chatUploadAttachments: [],
          chatDailyGuideStage: '',
          chatDailyGuidePendingPrompt: '',
          chatDailyGuidePendingTitle: '',
          chatDailyGuideReminderSuppressed: false,
          chatComposerDecision: null,
          _chatUploadAttachmentTimers: {},
          approvalDecisionTick: 0,
          /** 输入框内 @ / 触发：浮现引用或技能菜单 */
          chatInputTriggerOpen: false,
          chatInputTriggerKind: null,
          chatTriggerFilter: '',
          chatInputAtRail: 'raw',
          chatAtMenuPanel: 'categories',
          chatAtFloaterStyle: {},
          _chatInputBlurTimer: null,
          _chatAtFloaterReposBound: null,
          sessionHistory: [],
          historyDropdownOpen: false,
          /** 当前预置历史对话 id */
          activeChatScenarioId: '',
          /** 模型排队：输入框上方悬浮提示 */
          chatQueueNotice: { visible: false, position: 0 },
          _chatQueuePollIv: null,
          presetSuggestions,
          chatDemoScenarios: CHAT_DEMO_SCENARIOS,
          selectedMaterialId: null,
          sourcesLeftView: 'list',
          sourcesRightView: 'list',
          workbenchLeftPrimaryTab: 'material',
          sourcesLeftFullscreen: false,
          fullscreenMaterialId: null,
          fullscreenLeftView: 'list',
          fullscreenSelectedSourceId: null,
          fullscreenHighlightSourceId: null,
          fullscreenHighlightExcerptIndex: null,
          fullscreenExcerptRefs: {},
          fullscreenOriginalHighlight: null,
          fullscreenOriginalPageRefs: {},
          fullscreenOriginalRowRefs: {},
          citationPopover: { show: false, title: '', excerpt: '', x: 0, y: 0 },
          citationPopoverTimer: null,
          sourceGuideOpen: true,
          resourceDrawerOpen: { file: true, database: false, graph: false, knowledge: false },
          resourceDrawerContentHeights: { file: 1, database: 1, graph: 1, knowledge: 1 },
          resourceDrawerBodyEls: { file: null, database: null, graph: null, knowledge: null },
          dbResourceSearchQuery: '',
          graphResourceSearchQuery: '',
          selectedResourcePreview: null,
          resourcePreviewTab: 'schema',
          wbDetailBasicInfoModalOpen: false,
          wbDetailBasicInfoModalTitle: '详情',
          wbDetailBasicInfoModalRows: [],
          /** 工作台侧栏：已加入的数据表扁平行（每项一张表）；默认内置 3 条模拟数据，可继续经由「添加库表」向导勾选加入 */
          dbResourceList: DEMO_WORKBENCH_DB_RESOURCE_LIST.map((row) => ({ ...row })),
          /** 添加库表向导：可选数据源全集 */
          dbCatalogs: DEMO_WORKBENCH_DB_CATALOGS,
          wbDbAddModalOpen: false,
          wbDbAddCatalogId: undefined,
          wbDbAddSelectedTableNames: [],
          wbDbAddTableSearchQuery: '',
          wbGraphAddModalOpen: false,
          wbGraphAddSelectedIds: [],
          wbGraphDetailModalOpen: false,
          wbGraphDetailRecord: null,
          wbGraphDetailActiveTab: 'basic',
          /** 数据库抽屉：按库分组展开状态，key 为 databaseId；缺省视为展开 */
          workbenchDbTableGroupExpanded: {},
          graphResourceList: DEMO_WORKBENCH_GRAPH_RESOURCE_LIST.map((row) => ({ ...row })),
          graphCatalogs: DEMO_WORKBENCH_GRAPH_CATALOGS.map((row) => ({ ...row })),
          knowledgeResourceList: DEMO_WORKBENCH_KNOWLEDGE_RESOURCE_LIST.map((row) => ({ ...row })),
          highlightSourceId: null,
          highlightExcerptIndex: null,
          sourcesCollapsed: false,
          studioCollapsed: false,
          /** v2 外壳：'' | 'v2' */
          workbenchEmbedMode: '',
          /** v2 右 rail 当前面板：file | database | graph | knowledge | result */
          workbenchV2RightPanel: null,
          /** v2 右抽屉默认收起 */
          workbenchV2RightDrawerCollapsed: true,
          /** v2 详情侧栏：已打开的资料/资源/结果/抽取页签 */
          workbenchV2DetailTabs: [],
          workbenchV2DetailActiveTabKey: null,
          /** v2 详情页签内层 Tab 状态（基本信息/文件预览等），按页签 key 存储 */
          workbenchV2DetailTabInnerState: {},
          /** v2 详情 Teleport 锚点是否已挂载（晚于 capability-host 时需延迟 Teleport） */
          workbenchV2DetailHostReady: false,
          /** v2 目录 Teleport 锚点是否已挂载 */
          workbenchV2RightDrawerHostReady: false,
          sourcesWidth: 300,
          sourcesDetailWidth: 450,
          studioWidth: 340,
          rightSplitTaskPct: 33.333,
          rightSplitBatchTaskPct: 66.666,
          resizing: null,
          lastDetailFocus: null,
          excerptRefs: {},
          toastMessage: '',
          layoutMode: 'A',
          experienceDrafts: { extract: '', analysis: '', report: '' },
          hoveredMaterialId: null,
          treeSectionOpen: { material: true, analysis: true },
          selectedTreeNode: null,
          treeContextMenuNode: null,
          treeContextMenuVisible: false,
          treeContextMenuPosition: { x: 0, y: 0 },
          extractionResults: [],
          selectedExtractionId: null,
          summaryTemplateTasks: [],
          summarySkillTaskByTemplateId: {},
          summaryTaskResultModalVisible: false,
          summaryTaskResultTaskId: null,
          summaryTaskResultExpandedRuleId: '',
          summaryTaskResultForm: { name: '', extractionRules: [], analysisRule: '' },
          analysisTemplatePool: {
            public: SKILL_SEED_PUBLIC.map((x) => toAnalysisTemplateShared(x, 'public')),
            private: demoSharedPrivateAnalysisTemplatePool,
          },
          wbSelectedTemplateKey: '',
          wbSkillSidebarSearchKeyword: '',
          wbSkillSidebarSearchOpen: false,
          /** 侧栏技能行「更多」菜单：受控 open，供右键与三点按钮共用 */
          wbSkillTreeActionMenuKey: null,
          wbProjectSkillDetailModalOpen: false,
          wbProjectSkillCreateBasicModalOpen: false,
          wbProjectSkillCreateBasicSubmitting: false,
          wbProjectSkillCreateBasicForm: { name: '', description: '', tags: [] },
          wbProjectSkillDetailActiveTab: 'basic',
          wbProjectSkillDetailModalIsCreate: false,
          wbProjectSkillDetailReadOnly: false,
          _wbProjectSkillModalSnapshot: null,
          wbProjectSkillReadonlyPreview: null,
          wbSkillResourcePopoverOpen: false,
          wbSkillResourcePopoverSkillId: '',
          wbTaskCreateModalOpen: false,
          wbPackageDownloadModalOpen: false,
          wbPackageDownloadTarget: null,
          wbPackageDownloadForm: {
            taskName: '',
            structureMode: 'keep',
            formatMode: 'raw',
          },
          wbTaskCreateStep: 1,
          /** 任务指令：idle 待配置 | generating 生成中 | ready 可编辑 */
          wbTaskCreateInstructionState: 'idle',
          _wbTaskCreateInstructionTimer: null,
          _wbTaskCreateInstructionGenToken: 0,
          wbTaskListView: 'main',
          wbActiveBatchParentId: '',
          wbBatchChildStatusView: 'all',
          wbBatchChildPage: 1,
          wbBatchChildPageSize: 5,
          wbTaskRerunConfirmOpen: false,
          wbTaskRerunConfirmTarget: null,
          wbTaskRerunConfirmMode: 'task',
          wbTaskRerunConfirmDisposition: 'keep',
          wbTaskCreateForm: {
            taskName: '',
            skillId: '',
            taskType: 'single',
            resultOutputFolderId: WB_TASK_CREATE_RESULT_OUTPUT_ROOT,
            instruction: '',
            dataSourceFile: null,
            idColumns: [],
            subtaskNamingMode: 'same_as_object',
            subtaskNamingColumns: [],
            resourceTab: 'file',
            resourceQuery: '',
            fileExpandedKeys: [],
            resultExpandedKeys: [],
            selectedResources: [],
          },
          /** 生成技能：配置弹窗与推荐占位（演示） */
          wbGenerateSkillConfigModalOpen: false,
          wbGenerateSkillIntentText: '',
          wbGenerateSkillRecommendationItems: [],
          _wbGenerateSkillRecoTimers: null,
          workbenchCreatedTasks: [],
          wbProjectSkillResourcePaneEditing: false,
          _wbProjectSkillBasicPaneSnap: null,
          _wbProjectSkillConfigPaneSnap: null,
          _wbProjectSkillResourcePaneSnap: null,
          _wbProjectSkillCreateCommitted: false,
          _wbProjectSkillCreateAwaitingBasic: false,
          wbProjectSkillDetailId: '',
          wbProjectSkillConfigNavKey: 'rule',
          wbProjectSkillConfigTreeExpandedKeys: [],
          wbProjectSkillForm: { id: '', name: '', description: '', tags: [] },
        };
      ;
    },
  };
})();
